
//----------------------------------------------------
// The following code was generated by C# CUP v0.1
// 27.09.2003 13:58:24
//----------------------------------------------------

namespace Analizador_Lexico
{
    /**  class containing symbol constants. */
    public class sym
    {
        /* terminals */



        public const int CLASS = 1;//"class"
        public const int CONST = 2; //"const"
        public const int COR_A = 3;//"{"
        public const int COR_C = 4;  //"}"
        public const int IGUAL = 5; //"="
        public const int PYCOMA = 6; //";"
        public const int COMA = 7;  //","
        public const int VOID = 8;  //"void"
        public const int P_ABI = 9;  //"("
        public const int P_CER = 10; //")"
        public const int C_ABI = 11; //"["
        public const int C_CER = 12;  //"]"
        public const int SUM_SUM = 13; //"++"
        public const int IGU_IGU = 14; //"--"
        public const int IF = 15; //"if"
        public const int FOR = 16; //"for"
        public const int WHILE = 17;  // "while"
        public const int ELSE = 18; //"else"
        public const int BREAK = 19; //"break"
        public const int RETURN = 20; //"return"
        public const int READ = 21;  //"read"
        public const int WRITE = 22; //"write"
        public const int O_O = 23; //"||"
        public const int Y_Y = 24;  //"&&"
        public const int NEW = 25; //"new"
        public const int PUNTO = 26; //"."
        public const int IG_IG = 27; //"=="
        public const int DIF_IG = 28; //"!="
        public const int MAY = 29; //">"
        public const int MAY_IG = 30; //">="
        public const int MEN = 31; //"<"
        public const int MEN_IG = 32; //"<="
        public const int SUM = 33; //"+"
        public const int RES = 34; // "-"
        public const int POR = 35; //"*"
        public const int DIV = 36; // "/"
        public const int PORC = 37; // "%"
        public const int ID = 38; //ID
        public const int NUM = 39; //NUM
        public const int TRUE = 40; //TRUE
        public const int FALSE = 41; //FALSE
        public const int CHARCONS = 42; //CONS
        public const int EOF = 43;//EOF

    }
}